on:
  push:
    branches: [time-feature]
  pull_request:
    branches: [main]
 workflow_dispatch: 

jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}

    strategy:
        fail-fast: false
        matrix:
          zig-version:
              - "0.16.0"
          operating-system: [ ubuntu-latest, macos-latest, windows-latest ]
          optimize:
            - "Debug"
            - "ReleaseSafe"
            - "ReleaseFast"
            - "ReleaseSmall"
          options:
            - ""
            - "-Djit_always_on -Djit_asynchronous=false"
            - "-Djit_hotspot_always_on -Djit_asynchronous=false"
    
    steps:
      - name: Checkout project
        uses: actions/checkout@v6.0.2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Setup Zig
        uses: mlugg/setup-zig@v2.2.1
        with:
          version: ${{ matrix.zig-version }}
      - name: Build
        run: zig build -Doptimize=${{ matrix.optimize }} ${{ matrix.options }}
      - name: Run tests ${{ matrix.optimize }}
        run: zig build -Doptimize=${{ matrix.optimize }} ${{ matrix.options }} test
      - name: Run behavior tests ${{ matrix.optimize }}
        run: zig build -Doptimize=${{ matrix.optimize }} ${{ matrix.options }} test-behavior
 
  wasm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v6.0.2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Setup nightly Zig
        uses: mlugg/setup-zig@v2.2.1
        with:
          version: ${{ matrix.zig-version }}
      - name: Build for wasm
        run: zig build -Dtarget=wasm32-freestanding -Doptimize=ReleaseSmall

  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Setup Zig
        uses: mlugg/setup-zig@v2.2.1
        with:
          version: ${{ matrix.zig-version }}
      - run: zig fmt --check src/*.zig src/**/*.zig
